-- Drop Fact Table
DROP TABLE Fact_Patient_Health;

-- Drop Dimension Tables
DROP TABLE Dim_Patient;
DROP TABLE Dim_ChestPainType;
DROP TABLE Dim_RestingECG;
DROP TABLE Dim_ExerciseAngina;
DROP TABLE Dim_ST_Slope;

-- Create Dim_Patient
CREATE TABLE Dim_Patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age NUMBER,
    sex VARCHAR2(1),
    UNIQUE (age, sex)
);

-- Create Dim_ChestPainType
CREATE TABLE Dim_ChestPainType (
    chest_pain_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chest_pain_type VARCHAR2(10) UNIQUE
);

-- Create Dim_RestingECG
CREATE TABLE Dim_RestingECG (
    resting_ecg_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resting_ecg VARCHAR2(10) UNIQUE
);

-- Create Dim_ExerciseAngina
CREATE TABLE Dim_ExerciseAngina (
    exercise_angina_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_angina VARCHAR2(1) UNIQUE
);

-- Create Dim_ST_Slope
CREATE TABLE Dim_ST_Slope (
    st_slope_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    st_slope VARCHAR2(10) UNIQUE
);

-- Create Fact_Patient_Health
CREATE TABLE Fact_Patient_Health (
    fact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    age NUMBER,
    sex VARCHAR2(1),
    resting_bp NUMBER,
    cholesterol NUMBER,
    fasting_bs NUMBER,
    max_hr NUMBER,
    oldpeak NUMBER,
    heart_disease NUMBER,
    chest_pain_type_id NUMBER,
    resting_ecg_id NUMBER,
    exercise_angina_id NUMBER,
    st_slope_id NUMBER,
    FOREIGN KEY (patient_id) REFERENCES Dim_Patient(patient_id),
    FOREIGN KEY (chest_pain_type_id) REFERENCES Dim_ChestPainType(chest_pain_type_id),
    FOREIGN KEY (resting_ecg_id) REFERENCES Dim_RestingECG(resting_ecg_id),
    FOREIGN KEY (exercise_angina_id) REFERENCES Dim_ExerciseAngina(exercise_angina_id),
    FOREIGN KEY (st_slope_id) REFERENCES Dim_ST_Slope(st_slope_id)
);


-- Populate Dim_Patient
INSERT INTO Dim_Patient (age, sex)
SELECT DISTINCT Age, Sex FROM heart_stroke_data;

-- Populate Dim_ChestPainType
INSERT INTO Dim_ChestPainType (chest_pain_type)
SELECT DISTINCT ChestPainType FROM heart_stroke_data;

-- Populate Dim_RestingECG
INSERT INTO Dim_RestingECG (resting_ecg)
SELECT DISTINCT RestingECG FROM heart_stroke_data;

-- Populate Dim_ExerciseAngina
INSERT INTO Dim_ExerciseAngina (exercise_angina)
SELECT DISTINCT ExerciseAngina FROM heart_stroke_data;

-- Populate Dim_ST_Slope
INSERT INTO Dim_ST_Slope (st_slope)
SELECT DISTINCT ST_Slope FROM heart_stroke_data;


-- Populate Fact_Patient_Health
INSERT INTO Fact_Patient_Health (patient_id, age, sex, resting_bp, cholesterol, fasting_bs, max_hr, oldpeak, heart_disease, chest_pain_type_id, resting_ecg_id, exercise_angina_id, st_slope_id)
SELECT 
    p.patient_id,
    h.Age,
    h.Sex,
    h.RestingBP,
    h.Cholesterol,
    h.FastingBS,
    h.MaxHR,
    h.Oldpeak,
    h.HeartDisease,
    cpt.chest_pain_type_id,
    recg.resting_ecg_id,
    ea.exercise_angina_id,
    sts.st_slope_id
FROM 
    heart_stroke_data h
JOIN 
    Dim_Patient p ON h.Age = p.age AND h.Sex = p.sex
JOIN 
    Dim_ChestPainType cpt ON h.ChestPainType = cpt.chest_pain_type
JOIN 
    Dim_RestingECG recg ON h.RestingECG = recg.resting_ecg
JOIN 
    Dim_ExerciseAngina ea ON h.ExerciseAngina = ea.exercise_angina
JOIN 
    Dim_ST_Slope sts ON h.ST_Slope = sts.st_slope;
    
--SQL Query 1: Distribution of Heart Disease by Age
SELECT 
    Age, 
    HeartDisease, 
    COUNT(*) AS count
FROM 
    heart_stroke_data
GROUP BY 
    Age, HeartDisease
ORDER BY 
    Age;

--SQL Query 2: Average Cholesterol Levels by Chest Pain Type
SELECT 
    ChestPainType, 
    AVG(Cholesterol) AS avg_cholesterol
FROM 
    heart_stroke_data
GROUP BY 
    ChestPainType
ORDER BY 
    ChestPainType;

